[workspace]
members = [
    "db", "server",
    "tracking",
]

[workspace.dependencies]
db = { version = "0.1.0", path = "db" }
tracking = { version = "0.1.0", path = "tracking" }
server = { version= "0.1.0", path = "server" }